# Generated by Django 5.1.6 on 2025-03-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('warehouse', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('units_shipped', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('supplier_utilization', models.FloatField()),
                ('warehouse_utilization', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
